pipeline {

    agent any


    options {

        timestamps()

        disableConcurrentBuilds()

        buildDiscarder(
            logRotator(
                numToKeepStr: '20',
                artifactNumToKeepStr: '10'
            )
        )
    }


    environment {

        SERVICE_NAME = "account-service"

        IMAGE_NAME = "satyamgrao007/lovable-account-service"

        NAMESPACE = "lovable-core"

    }


    stages {


        stage('Checkout Source') {

            steps {

                checkout scm

            }
        }



        stage('Prepare Maven Wrapper') {

            steps {

                sh '''
                    chmod +x common-lib/mvnw
                    chmod +x account-service/mvnw
                '''

            }
        }



        stage('Verify Environment') {

            steps {

                sh '''

                    echo "========== Java =========="
                    java -version


                    echo "========== Maven =========="
                    ./account-service/mvnw -version


                    echo "========== Git =========="
                    git --version


                    echo "========== Docker =========="
                    docker --version
                    docker ps

                '''

            }
        }



        stage('Build Common Library') {

            steps {

                dir('common-lib') {

                    sh '''

                        ./mvnw clean install -DskipTests

                    '''

                }

            }

        }




        stage('Build and Push Image using Jib') {

            steps {


                withCredentials([

                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )

                ]) {


                    dir('account-service') {


                        sh '''

                        echo "Building Docker image with Jib"


                        ./mvnw compile jib:build \
                        -Djib.to.image=${IMAGE_NAME}:${BUILD_NUMBER} \
                        -Djib.to.tags=latest \
                        -Djib.to.auth.username=$DOCKER_USERNAME \
                        -Djib.to.auth.password=$DOCKER_PASSWORD


                        echo "Image pushed successfully"

                        '''

                    }

                }

            }

        }



        stage('Deploy Kubernetes') {

            steps {

                sh """

                echo "Deploying ${SERVICE_NAME}"


                kubectl set image deployment/${SERVICE_NAME} \
                ${SERVICE_NAME}=${IMAGE_NAME}:${BUILD_NUMBER} \
                -n ${NAMESPACE}


                kubectl rollout status deployment/${SERVICE_NAME} \
                -n ${NAMESPACE}


                """

            }

        }



    }



    post {


        success {

            echo """

            ======================================
                 BUILD SUCCESSFUL
            ======================================

            Service:
            ${SERVICE_NAME}


            Image:
            ${IMAGE_NAME}:${BUILD_NUMBER}


            """

        }



        failure {

            echo """

            ======================================
                 BUILD FAILED
            ======================================


            """

        }



        always {

            deleteDir()

        }

    }

}